---
name: Reusable .NET Build & Verify Tests Pass

on:  # yamllint disable-line rule:truthy
  workflow_call:
    inputs:
      dotnet-versions:
        description: "SDK versions to install"
        required: false
        type: string
        default: 10.x
      configuration:
        description: "Build configuration"
        required: false
        type: string
        default: Release
      version:
        description: "Package version"
        required: true
        type: string
      source-directory:
        description: "Relative directory where source code is located"
        required: false
        type: string
        default: .
      artifact-name:
        description: "Name of the artifact to upload"
        required: false
        type: string
        default: Packages
jobs:
  build-and-verify:
    runs-on: ubuntu-latest
    name: Build and verify tests pass
    defaults:
      run:
        working-directory: ${{ inputs.source-directory }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Setup .NET SDK
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: ${{ inputs.dotnet-versions }}
          cache: true
          cache-dependency-path: '**/packages.lock.json'

      - name: Restore dependencies
        shell: pwsh
        run: |
          dotnet restore

      - name: Build solution
        shell: pwsh
        run: |
          dotnet build --configuration ${{ inputs.configuration }} --no-restore

      - name: Run tests
        id: run-tests
        run: >
          dotnet test --configuration ${{ inputs.configuration }}
          --no-build --logger trx

      - name: Upload test results
        if: >
          ${{ steps.run-tests.outcome != 'skipped' &&
            steps.run-tests.outcome != 'cancelled' }}
        uses: actions/upload-artifact@v4
        with:
          name: test-results
          path: "**/*.trx"

      - name: Build packages
        run: >
          dotnet pack --configuration ${{ inputs.configuration }}
          -p:Version=${{ inputs.version }} -o bin/${{ inputs.configuration }}

      - name: Upload Nuget Packages as artifact
        uses: actions/upload-artifact@v4
        with:
          name: ${{ inputs.artifact-name }}
          path: "src/bin/${{ inputs.configuration }}/*.nupkg"
          if-no-files-found: error
